m_blockThreadExtent seems like it was removed or changed in alpaka (was a hack anyway)
Solves:
  imresh/benchmark/imresh/algorithms/cuda/cudaVectorReduce.tpp(225):
  error: class "alpaka::acc::AccGpuCudaRt<cupla::KernelDim,
  cupla::IdxType>" has no member "m_blockThreadExtent"
when compiling